title: Artin's Blog
subtitle: 谁有天大力气可以拎着自己飞呀
description: Python / React / Nodejs / ML
keywords: Python,ML,React,Nodejs
author: Artin
language: zh-CN
timezone: Asia/Shanghai

meta_generator: true
updated_option: 'date'

url: https://lengthmin.me
root: /
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false
  trailing_html: false

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: false # Open external links in new tab
  field: site # Apply to the whole site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false

highlight:
  enable: false

prismjs:
  enable: true
  line_number: true

index_generator:
  path: ""
  per_page: 10
  order_by: -date

default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm

per_page: 10
pagination_dir: page

theme: next

feed:
  type: rss2
  path: rss.xml
  limit: 0
  hub:

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

server:
  port: 48003
  log: false
  ip: 0.0.0.0
  compress: false
  header: true
  serveStatic:
    extensions:
      - html

deploy:
  - type: git
    repo:
      github: https://_GH_TOKEN_@github.com/lengthmin/lengthmin.me.git,gh-pages

sitemap:
  path: sitemap.xml
  tag: false
  category: false

symbols_count_time:
  symbols: true
  time: false
  total_symbols: false
  total_time: false
  exclude_codeblock: true
  awl: 4
  wpm: 275
  suffix: "mins."

markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: true
    breaks: false
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-abbr
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-footnote
    - markdown-it-cjk-breaks
    - markdown-it-container
  anchors:
    level: 2
    collisionSuffix: ''
    case: 0
    separator: '-'


theme_config:
  preconnect: true
  anchor:
    enable: true
    color: "#0e83cd"
    position: left # If left, anchors will always be visible.
    margin: 7px
    text: "#"
    icon:
      # If true, the `text` option will be ignored.
      enable: true
      font: "Font Awesome 5 Free"
      content: \f0c1

  cache:
    enable: false
  minify: true
  darkmode: false

  custom_file_path:
    head: data/head.njk
    # header: data/header.njk
    # sidebar: data/sidebar.njk
    # postMeta: data/post-meta.njk
    postBodyEnd: data/post-body-end.njk
    footer: data/footer.njk
    bodyEnd: data/body-end.njk
    # variable: data/variables.styl
    # mixin: data/mixins.styl
    style: data/styles.styl

  # ---------------------------------------------------------------
  # Site Information Settings
  # See: https://theme-next.org/docs/getting-started/
  # ---------------------------------------------------------------

  favicon:
    small: /images/favicon-16x16-next.png
    medium: /images/favicon-32x32-next.png
    apple_touch_icon: /images/apple-touch-icon-next.png
    safari_pinned_tab: /images/logo.svg
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml

  footer:
    # Specify the date when the site was setup. If not defined, current year will be used.
    since: 2016

    icon:
      name: fa fa-heart
      animated: true
      color: ""

    # If not defined, `author` from Hexo `_config.yml` will be used.
    copyright:

    powered: true

    # Beian ICP and gongan information for Chinese users. See: http://www.beian.miit.gov.cn, http://www.beian.gov.cn
    beian:
      enable: false
      icp:
      # The digit in the num of gongan beian.
      gongan_id:
      # The full num of gongan beian.
      gongan_num:
      # The icon for gongan beian. See: http://www.beian.gov.cn/portal/download
      gongan_icon_url:

  # scheme: Muse
  scheme: Mist

  # Mermaid tag
  mermaid:
    enable: true
    # Available themes: default | dark | forest | neutral
    theme: neutral

  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimiter is the target link, value after `||` delimiter is the name of Font Awesome icon.
  # When running the site in a subdirectory (e.g. yoursite.com/blog), remove the leading slash from link value (/archives -> archives).
  # External url should start with http:// or https://
  menu:
    home: / || fa fa-home
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fas fa-archive
    about: /about/ || fa fa-user
    友链: /friends/ || fa fa-link fa-fw
    #sitemap: /sitemap.xml || sitemap
    #commonweal: /404/ || heartbeat

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: false

  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------

  sidebar:
    # Sidebar Position.
    # position: left
    position: right

    # Manual define the sidebar width. If commented, will be default for:
    # Muse | Mist: 320
    # Pisces | Gemini: 240
    # width: 300

    # Sidebar Display (only for Muse | Mist), available values:
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically.
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  totally remove sidebar including sidebar toggle.
    display: always

    padding: 18
    offset: 12
    onmobile: false

  avatar:
    url: /images/avatar.png
    rounded: false
    rotated: false

  social:
    E-Mail: mailto:lengthmin@gmail.com || fa fa-envelope
    GitHub: https://github.com/lengthmin || fab fa-github
    Telegram: https://telegram.me/lengthmin || fab fa-telegram
    RSS: /rss.xml || fas fa-rss

  social_icons:
    enable: true
    icons_only: false
    transition: true

  toc:
    enable: true
    number: true
    wrap: false
    expand_all: false
    max_depth: 6

  excerpt_description: true

  read_more_btn: true

  post_meta:
    item_text: true
    created_at: true
    updated_at:
      enable: true
      another_day: true
    categories: true

  symbols_count_time:
    separated_meta: true
    item_text_post: true
    item_text_total: false

  reward_settings:
    enable: true
    animation: false
    comment: 如果您觉得有帮助的话，可以请我喝瓶饮料~

  reward:
    wechatpay: https://i.lengthm.in/qiafan/wechatpay.png
    alipay: https://i.lengthm.in/qiafan/alipay.jpg

  related_posts:
    enable: true
    title: # Custom header, leave empty to use the default one
    display_in_home: false
    params:
      maxCount: 3
      #PPMixingRate: 0.0
      isDate: false
      #isImage: false
      #isExcerpt: false

  # Show previous post and next post in post footer if exists
  # Available values: left | right | false
  post_navigation: right

  # ---------------------------------------------------------------
  # Custom Page Settings
  # See: https://theme-next.org/docs/theme-settings/custom-pages
  # ---------------------------------------------------------------

  # TagCloud settings for tags page.
  tagcloud:
    # All values below are same as default, change them by yourself.
    min: 12 # Minimun font size in px
    max: 30 # Maxium font size in px
    start: "#ccc" # Start color (hex, rgba, hsla or color keywords)
    end: "#111" # End color (hex, rgba, hsla or color keywords)
    amount: 200 # Amount of tags, change it if you have more than 200 tags

  # Set the text alignment in posts / pages.
  text_align:
    # Available values: start | end | left | right | center | justify | justify-all | match-parent
    desktop: justify
    mobile: justify

  # Reduce padding / margin indents on devices with narrow width.
  mobile_layout_economy: false

  # Android Chrome header panel color ($brand-bg / $headband-bg => $black-deep).
  android_chrome_color: "#222"

  codeblock:
    # Code Highlight theme
    # All available themes: https://theme-next.js.org/highlight/
    theme:
      light: default
      dark: tomorrow-night
    prism:
      light: prism
      dark: prism-dark
    # Add copy button on codeblock
    copy_button:
      enable: true
      # Available values: default | flat | mac
      style: flat

  # Follow me on GitHub banner in right-top corner.
  github_banner:
    enable: true
    permalink: https://github.com/lengthmin
    title: Follow me on GitHub

  back2top:
    enable: true
    # Back to top in sidebar.
    sidebar: false
    # Scroll percent label in b2t button.
    scrollpercent: true

  # Reading progress bar
  reading_progress:
    enable: true
    # Available values: top | bottom
    position: top
    color: "#37c6c0"
    height: 3px
  
  nprogress:
    enable: true
    spinner: true
  
  disable_baidu_transformation: true

  canonical: true

  exturl: false

  google_site_verification:

  math:
    per_page: true

    mathjax:
      enable: false
      mhchem: false

    # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
    katex:
      enable: false
      # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
      copy_tex: false

  pjax: true

  mediumzoom: true

  lazyload: true

  pangu: true

  quicklink:
    enable: true

    # Home page and archive page can be controlled through home and archive options below.
    # This configuration item is independent of `enable`.
    home: true
    archive: true

    # Default (true) will initialize quicklink after the load event fires.
    delay: true
    # Custom a time in milliseconds by which the browser must execute prefetching.
    timeout: 3000
    # Default (true) will enable fetch() or falls back to XHR.
    priority: true

    # For more flexibility you can add some patterns (RegExp, Function, or Array) to ignores.
    # See: https://github.com/GoogleChromeLabs/quicklink#custom-ignore-patterns
    ignores:

  # Multiple Comment System Support
  comments:
    # Available values: tabs | buttons
    style: tabs
    # Choose a comment system to be displayed by default.
    # Available values: changyan | disqus | disqusjs | gitalk | livere | valine
    active: disqus
    # Setting `true` means remembering the comment system selected by the visitor.
    storage: true
    # Lazyload all comment systems.
    lazyload: false
    # Modify texts or order for any navs, here are some examples.
    nav:
      #disqus:
      #  text: Load Disqus
      #  order: -1
      #gitalk:
      #  order: -2

  # DisqusJS
  # For more information: https://github.com/SukkaW/DisqusJS
  disqusjs:
    enable: true
    api: https://disqus.skk.moe/disqus/
    apikey: _disqusjs_apikey_
    shortname: _disqusjs_shortname_

  cfga:
    tracking_id: _google_analytics_tracking_id_
    localhost_ignored: true

  # Show Views / Visitors of the website / page with busuanzi.
  # Get more information on http://ibruce.info/2015/04/04/busuanzi
  busuanzi_count:
    enable: true
    total_visitors: true
    total_visitors_icon: fa fa-user
    total_views: true
    total_views_icon: fa fa-eye
    post_views: true
    post_views_icon: fa fa-eye

  local_search:
    enable: true
    # If auto, trigger search by changing input.
    # If manual, trigger search by pressing enter key or search button.
    trigger: auto
    # Show top n results per article, show all results by setting to -1
    top_n_per_article: 3
    # Unescape html strings to the readable one.
    unescape: true
    # Preload the search data when the page loads.
    preload: true

  # ---------------------------------------------------------------
  # Tags Settings
  # See: https://theme-next.org/docs/tag-plugins/
  # ---------------------------------------------------------------

  # Note tag (bs-callout)
  note:
    # Note tag style values:
    #  - simple    bs-callout old alert style. Default.
    #  - modern    bs-callout new (v2-v3) alert style.
    #  - flat      flat callout style with background, like on Mozilla or StackOverflow.
    #  - disabled  disable all CSS styles import of note tag.
    style: simple
    icons: false
    # Offset lighter of background in % for modern and flat styles (modern: -12 | 12; flat: -18 | 6).
    # Offset also applied to label tag variables. This option can work with disabled note tag.
    light_bg_offset: 0

  # Tabs tag
  tabs:
    transition:
      tabs: false
      labels: true

  # Use velocity to animate everything.
  # For more information: http://velocityjs.org
  motion:
    enable: false
    async: false
    transition:
      # Transition variants:
      # fadeIn | flipXIn | flipYIn | flipBounceXIn | flipBounceYIn
      # swoopIn | whirlIn | shrinkIn | expandIn
      # bounceIn | bounceUpIn | bounceDownIn | bounceLeftIn | bounceRightIn
      # slideUpIn | slideDownIn | slideLeftIn | slideRightIn
      # slideUpBigIn | slideDownBigIn | slideLeftBigIn | slideRightBigIn
      # perspectiveUpIn | perspectiveDownIn | perspectiveLeftIn | perspectiveRightIn
      post_block: fadeIn
      post_header: slideDownIn
      post_body: slideDownIn
      coll_header: slideLeftIn
      # Only for Pisces | Gemini.
      sidebar: slideUpIn

  font:
    enable: false

    # Uri of fonts host, e.g. //fonts.googleapis.com (Default).
    host: https://fonts.loli.net

    # Font options:
    # `external: true` will load this font family from `host` above.
    # `family: Times New Roman`. Without any quotes.
    # `size: x.x`. Use `em` as unit. Default: 1 (16px)

    # Global font settings used for all elements inside <body>.
    global:
      external: true
      family: Lato
      size:

    # Font settings for site title (.site-title).
    title:
      external: true
      family:
      size:

    # Font settings for headlines (<h1> to <h6>).
    headings:
      external: true
      family:
      size:

    # Font settings for posts (.post-body).
    posts:
      external: true
      family:

    # Font settings for <code> and code blocks.
    codes:
      external: true
      family:

  vendors:
    _internal: lib
    plugins: jsdelivr
